# name: aur-qusb2snes-git update

# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

# jobs:
#   aur-qusb2snes-git:
#     uses: ./.github/workflows/aur-workflow.yml
#     with:
#       package_name: qusb2snes-git
#     secrets: inherit
